
(* General *)
let cNUM_TEAMS = 2
let cUPDATE_TIME = 0.05
let cMAX_WAIT_CONNECTION_TIME = 10.
let cDEFAULT_PORT_NUMBER = 10500
let cDEFAULT_GUI_PORT_NUMBER = 10501
let cDEFAULT_BOT_PORT_NUMBER = 10502

(* Board *)
let cTIME_LIMIT = 124.
let cBOARD_WIDTH = 600.
let cBOARD_HEIGHT = 600.
let cBOARD_SIZE = (cBOARD_WIDTH, cBOARD_HEIGHT)

let cNUM_COLUMNS = 25
let cNUM_ROWS = 25

let cTILE_WIDTH = cBOARD_WIDTH /. (float cNUM_COLUMNS)
let cTILE_HEIGHT = cBOARD_HEIGHT /. (float cNUM_ROWS)

let cNUM_INITIAL_TEAM_RIDERS = 2

let cNUM_INITIAL_TEAM_SHIELD = 2
let cNUM_INITIAL_TEAM_INVINCIBILITY = 0

let cNUM_INITIAL_FIELD_SHIELD = 10
let cNUM_INITIAL_FIELD_INVINCIBILITY = 5 

let cINVINCIBILITY_TIME = 5
